import img1 from "../../assets/G2.png";
import img2 from "../../assets/G1.png";
import img3 from "../../assets/slide10.png";
import img4 from "../../assets/slide11.png";

export const hoteldata = [
  {
    image: img4,
    image1: img3,
    image2: img2,
    image3: img1,
    texts: "GUEST",
    text1: "Symphony Samundra Beachside Jungle Resort & Spa",
    text2: "310 M From Chidya Tapu",
    text3: "Jungle views with free Breakfast",
    text4: "Good Service Quality",
    text: "Sc Rooms",
    rate: "$726",
    rate1: "$438",
    rate2: "$210 Taxes & Fees",
  },
  {
    image: img4,
    image1: img3,
    image2: img2,
    image3: img1,
    texts: "GUEST",
    text1: "Symphony Samundra Beachside Jungle Resort & Spa",
    text2: "310 M From Chidya Tapu",
    text3: "Jungle views with free Breakfast",
    text4: "Good Service Quality",
    text: "Sc Rooms",
    rate: "$726",
    rate1: "$438",
    rate2: "$210 Taxes & Fees",
  },
  {
    image: img4,
    image1: img3,
    image2: img2,
    image3: img1,
    texts: "GUEST",
    text1: "Symphony Samundra Beachside Jungle Resort & Spa",
    text2: "310 M From Chidya Tapu",
    text3: "Jungle views with free Breakfast",
    text4: "Good Service Quality",
    text: "Sc Rooms",
    rate: "$726",
    rate1: "$438",
    rate2: "$210 Taxes & Fees",
  },
  {
    image: img4,
    image1: img3,
    image2: img2,
    image3: img1,
    texts: "GUEST",
    text1: "Symphony Samundra Beachside Jungle Resort & Spa",
    text2: "310 M From Chidya Tapu",
    text3: "Jungle views with free Breakfast",
    text4: "Good Service Quality",
    text: "Sc Rooms",
    rate: "$726",
    rate1: "$438",
    rate2: "$210 Taxes & Fees",
  },
  {
    image: img4,
    image1: img3,
    image2: img2,
    image3: img1,
    texts: "GUEST",
    text1: "Symphony Samundra Beachside Jungle Resort & Spa",
    text2: "310 M From Chidya Tapu",
    text3: "Jungle views with free Breakfast",
    text4: "Good Service Quality",
    text: "Sc Rooms",
    rate: "$726",
    rate1: "$438",
    rate2: "$210 Taxes & Fees",
  },
];
