import suba1 from "../../assets/thirdsight1.png";
import fish from "../../assets/thirdsight2.png";
import fish1 from "../../assets/thirdsight3.png";
import location from "../../assets/greenlocation.svg";
import star from "../../assets/star.png";

export const thirdsight = [
  {
    id: 1,
    img: suba1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 2,
    img: fish,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 3,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 4,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 5,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 6,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Island Tour",
    text2: "Dinner",
    text3: "Ferry",
    text4: "Best Seller",
    text5: "Sightseeing",
    north: "Dinner Cruise with Live Music, Dinner & DJ",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
];
