import suba1 from "../../assets/suba1.png";
import fish from "../../assets/fish1.png";
import fish1 from "../../assets/fish2.png";
import location from "../../assets/greenlocation.svg";
import star from "../../assets/star.png";
export const second = [
  {
    id: 1,
    img: suba1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 2,
    img: fish,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 3,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 4,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 5,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 6,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
  {
    id: 7,
    img: fish1,
    text1: "Scuba Diving",
    text2: "Guide",
    text3: "Coordinator",
    text4: "Best Seller",
    text5: "Certificate",
    north: "Scuba Diving in North Bay Island",
    location: location,
    port: "Port Blair",
    lorem:
      "Enim nibh interdum amet mi aliquet mauris quam. Ullamcorper imperdiet felis, duis ornare. Nec, faucibus cras nascetur cursus sit. Viverra a, augue quam lacus at tincidunt purus.",
    star: star,
    dollar: "$349.00",
  },
];
